
# api ~
# Toss Payments API
api.toss.secret-key=test_sk_d46qopOB89PjPmxvpqZLrZmM75y0
api.toss.client-key=test_ck_KNbdOvk5rka22P9eoqA43n07xlzm
api.toss.base-url=https://api.tosspayments.com

# Kakao API
api.kakao.rest-api-key=ef14f9ed1b5503ba55eb325322c5bcdb
api.kakao.book-url=https://dapi.kakao.com/v3/search/book
api.kakao.map-url=
# Kakao Map JavaScript Key (for place search)
api.kakao.map.js-key=36186fd97daac4f2fe5626115f1993db

# Naver API
api.naver.client-id=
api.naver.client-secret=

# db migration : postgres -> mysql
#db.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#db.url=jdbc:log4jdbc:postgresql://secondary-book-db.ctacq0y0i2c0.ap-northeast-2.rds.amazonaws.com:5432/postgres
#db.username=postgres
#db.password=qorhqtlrp

db.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
db.url=jdbc:log4jdbc:mysql://localhost:3306/secondHandBook?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
db.username=root
db.password=11111111

#redis.host=master.secondarybook-redis.twovms.apn2.cache.amazonaws.com
#redis.port=6379
#redis.password=qorhqtlrpqorhqtlrp
#redis.ssl.enabled=true
redis.host=localhost
redis.port=6379
redis.password=
redis.ssl.enabled=false

file.dir=/Users/aaa/Downloads/secondaryBook/img


# Kakao OAuth
api.kakao.login-url=https://kauth.kakao.com
api.kakao.api-url=https://kapi.kakao.com
api.kakao.client.id=540d6c34f2540fb2c6e27bac5a1d8922
api.kakao.redirect.uri=https://www.shinhan6th.com/auth/kakao/callback
api.kakao.client_secret=LpbkbdOBiPV2uCjOFHFbvLqjxDtp8hVt

# Naver OAuth
api.naver.login-url=https://nid.naver.com
api.naver.api-url=https://openapi.naver.com
api.naver.client.id=oL6LgMzUNmjkaZ3kKGeS
api.naver.client.secret=eMXhkYrcBt
api.naver.redirect.uri=https://www.shinhan6th.com/auth/naver/callback

# Google SMTP
mail.username=rbxo3213@gmail.com
mail.password=yiphqydsokrlcmtk

#AWS S3
AWS_ACCESS_KEY=REMOVED
AWS_SECRET_ACCESS_KEY=REMOVED
AWS_S3_BUCKET=secondarybooksimages
AWS_S3_REGION=ap-northeast-2
AWS_CLOUDFRONT_DOMAIN=d3p8m254izebr5.cloudfront.net


admin.login.code1=qorhqtlrp
admin.login.code2=rptlrhqqo


aes.secret-key=jnF6J8oojo258LHoW2eRoL/moQzMFx2WJBVcBZu89BU=

# WebSocket CORS
app.cors.allowed-origins=https://www.shinhan6th.com,http://localhost:8080
